### ISSUE TITLE
Some folder is missing?

### ISSUE THREAD

**Issue by wojiaolianer** [laderast/bash_for_bioinformatics#1]
Holle, I am reading your article "bash for informatics", and I can't find some documents like /dx-run, have you deleted it?

**Comment by laderast** [comment]
Hi - thanks for finding this. Can you send me the links that aren't working? I will fix them.

**Comment by wojiaolianer** [comment]
https://laderast.github.io/bash_for_bioinformatics/04-doing-work-with-dx-run.html, some documents in your tutorial is missed? And I have a question while working with dx_toolkit, when I using "for" loop function, it get error. I look up RAP and your tutorial but have no idea to deal it, here is my bash script and error. Could you please help me, thanks much. 
![image](https://user-images.githubusercontent.com/61368277/217853407-09519ad7-1785-42f1-af6f-b8e169a0b22b.png)
![1675955904185](https://user-images.githubusercontent.com/61368277/217853815-93a37678-cd89-43f7-b5c1-ef90c31ceee0.png)

**Comment by laderast** [comment]
Ah - I provided the wrong url to clone in Chapter 2. You should run 

```
git clone https://github.com/laderast/bash_bioinfo_scripts
```
Instead of `bash_info_scripts`. That was my fault. I'm fixing that right now.

The `dx-run/` folder is in this repository.

It's hard for me to debug your code from a screenshot - if you post a question at https://community.dnanexus.com/ you'll probably get some help from the RAP team
